### PR TITLE
Feature/stephentan12/875810432-calendar

### PR DESCRIPTION
**Pull request by StephenTan12**
### Administrative Info

Monday Board ID: 851212620

### Changes

Frontend Changes:
- implemented calendar based off of agency data from the database
  - dynamically generated a unique color for each recurring event (used for FullCalendar and the toolbar)
  - parsed event data from the database to generate recurring events for FullCalendar
- implemented calendar toolbar to display events on the calendar
  - added search bar to search for specific agencies based on name
  - separated agency events by distribution and rescue categories

Backend Changes:
- added a GET route to fetch specific fields of each agency

### Testing

- put sample agency events into database and examined props and state to ensure proper rendering

### Confirmation of Change

Monthly View with Events
| ----------------------- |
| image]|

### CODE REVIEW

**Review by sblumin — COMMENTED** [review]
LGTM! Can you do me a favor and change the title of the app (in frontend/public/index.html) from React App to FSD Distribution Web App in this PR as well? Then will be all approved :)

**Review by sblumin — APPROVED** [review]
LGTM!! ty :)

**Review by ecflores30 — COMMENTED** [review]
Looks awesome: well done! Just some minor documentation changes

**Review by ecflores30 — APPROVED** [review]
LGTM! Awesome job y'all!

**Pull request merged**
