### PR TITLE
Testing/wllmwu/1262795886 write unit tests

### PR DESCRIPTION
**Pull request by wllmwu**
### Administrative Info

Monday Board ID: 851212620
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

- Updated AgencyProfileForm unit tests
- Added unit tests for Calendar component in AgencyProfileForm
- Updated Calendar component to work with event deletion
- Fix/refactor technical issues in backend agency and task routes

### Testing

How did you confirm your changes worked?

- Ran `npm test`
- Checked the Calendar component works as expected again

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| ----------------------- |
| [TODO Screenshot Link]  |

### CODE REVIEW

**Review by sblumin — COMMENTED** [review]
LGTM! Can you also delete test.json from root as well?

**Comment by wllmwu** [comment]
Whoops, forgot about that - just deleted it!

**Review by NirmalAgnihotri — APPROVED** [review]
Looks good to me! Good job on all the tests and changes to AgencyProfileForm.

**Review by sblumin — APPROVED** [review]
LGTM!

**Pull request merged**
