### PR TITLE
Feature/wllmwu/997819182 update form styling

### PR DESCRIPTION
**Pull request by wllmwu**
### Administrative Info

Monday Board ID: 851212620
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

BIG MAIN CHANGE:
- Implement adding/removing extra addresses and contacts, with gray highlighting

Other minor changes:
- Add catch-all route to the backend
- Clean up .gitignore and readme files

### Testing

How did you confirm your changes worked?

- Clicked the add and remove buttons a bunch of times
- Manually entered `localhost:8000/agency` and `localhost:8000/create-agency` into the URL bar
- Looked at the new readme and checked that `frontend/node_modules` etc. were not tracked by git

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Additional address
---
Additional contact
---
Tests

### CODE REVIEW

**Review by sblumin — COMMENTED** [review]
Everything looks good!! Before I approve, can you explain why you switched to FormRow and FormCol components?

**Comment by wllmwu** [comment]
> can you explain why you switched to FormRow and FormCol components?

Yeah, we removed bootstrap because it totally overrides a lot of CSS styling, and the original Row and Col components were from react-bootstrap. FormRow/Col replace them so we can do only the styling that we need. (also fixed CreateAgencyBtn because some of its styling apparently came from bootstrap)

**Review by sblumin — APPROVED** [review]
Thanks for clarifying that, LGTM!

**Review by ryanbuui — APPROVED** [review]
LGTM, nice work!

**Pull request merged**
